spring.application.name=ratemy
server.tomcat.accesslog.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d8qrvn37uimc73ebq17g-a/database_uskr
spring.datasource.username=database_uskr_user

spring.datasource.password=JkSdUUNOofRBkU9HtSsCBnEeUUgtZSyx